version: "3.9"
services:
  web:
    build: .
    ports:
      - "9090:9090"
    container_name: mbsapp
    depends_on:
      - mbsdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://(endpoint link)/(database name which is inside the new server)
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=(password of newly created server)
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  mbsdb:
    image: postgres:14.1-alpine
    restart: always
    container_name: mbsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=(password of newly created server)
      - POSTGRES_DB=(database name which is inside the new server)
    ports:
      - "5432:5432"
